#!/bin/sh
echo "[pre-commit] fired, branch=$(git rev-parse --abbrev-ref HEAD)" >> /tmp/hook-debug.log
ls .git/MERGE_HEAD .git/MERGE_MSG .git/MERGE_HEAD 2>&1 >> /tmp/hook-debug.log
echo "GIT_REFLOG_ACTION=$GIT_REFLOG_ACTION" >> /tmp/hook-debug.log
exit 0
